apiVersion: v1
kind: Service
metadata:
  name: checkride
  namespace: checkride
  labels:
    app: checkride
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: checkride
