---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkride
  namespace: checkride
  labels:
    app: checkride
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkride
  template:
    metadata:
      labels:
        app: checkride
    spec:
      containers:
      - name: checkride
        image: gcr.io/popori-gcct-pj/checkride:3c5dca8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
